name: cd pipeline

on:
  workflow_run:
    workflows: ["docker image ci"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted  
    steps:
      - name: pull docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/testcicd-flower:latest
        
      - name: Delete old container
        run: sudo docker rm -f testcicd-flower-container || true
        
      - name: Run new container
        run: |
          sudo docker run -d -p 3000:3000 --name testcicd-flower-container ${{ secrets.DOCKER_USERNAME }}/testcicd-flower
          sleep 5
          sudo docker ps -a
          sudo docker logs testcicd-flower-container